FROM node:latest

RUN apt-get update -qq && apt-get install -yqq \
  build-essential \
  git \
  libgtk2.0-0 \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  python \
  xvfb

